client_config_backend: settings
#client_config_file: {{str}}
client_config:
  client_id: {{str}}
  client_secret: {{str}}
  auth_uri: {{str}}
  token_uri: {{str}}
#  redirect_uri: {{str}}
#  revoke_uri: {{str}}

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json

get_refresh_token: False
#  - {{str}}